@baseUrl = http://localhost:3000/api/v1

### Register admin
POST {{baseUrl}}/auth/email/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "secret",
  "firstName": "Admin",
  "lastName": "User"
}

### Login admin
# @name adminLogin
POST {{baseUrl}}/auth/email/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "secret"
}

### Get token
@adminToken = {{adminLogin.response.body.token}}

### Get information about yourself
GET {{baseUrl}}/auth/me
Authorization: Bearer {{adminToken}}

### Get all users
GET {{baseUrl}}/users?page=1&limit=10
Authorization: Bearer {{adminToken}}
